### ISSUE TITLE
ICAL Scraper

### ISSUE THREAD

**Issue by AvocadoMoon** [AvocadoMoon/EventScraper#16]
Create iCal scraper which allows remote iCal's to be a source of information.

### Task:

- [x] Create the scraper
- [x] Have location behave appropriately
- [x] Add a test for scraper correctness
